### ISSUE TITLE
404 log has grown to over 70k entries due to bots

### ISSUE THREAD

**Issue by websbydrew** [kunalnagar/custom-404-pro#12]
I cant delete the log, it hangs up each time. Can I delete log from terminal maybe?

**Comment by kunalnagar** [comment]
I'll be fixing this in the next release. 

Just click the Clear Log button and if you get a white screen, just go back and click Clear again. It is clearing the logs but it is timing out. A couple of tries and you should be good to go.

**Comment by websbydrew** [comment]
It deletes no logs I've tested.

**Comment by AndrewCalvo** [comment]
I'm having this same problem. I have 99,000 logs which I am trying to clear but it times out within a matter of seconds.

**Comment by kunalnagar** [comment]
@AndrewCalvo @websbydrew Released an update (1.4.3). Once you've updated – instead of the check box for clearing logs now, there is a button called "Clear Logs". Please click on it and it will clear your logs. It might take some time but once it is done, you will get an alert saying "Logs Deleted".

Let me know if it works for you. It might take some time though.

**Comment by AndrewCalvo** [comment]
Thanks Kunal, 
I just had an opportunity to update the plugin, and while I do see the button - clicking it does nothing. It doesn't send a query to the server or do I get any type of indication that it is deleting logs in the background.

**Comment by kunalnagar** [comment]
@AndrewCalvo so the button deletes logs incrementally in groups of 500. Here's something you can do to check if logs are being deleted or not. Open the Logs section and take a look at the number of logs. Then go to Settings in another tab and Clear the Logs. After a minute or so, refresh the Logs tab and see if any have been deleted. I'm unable to test with 70k logs at the moment. Thanks for your help.

**Comment by AndrewCalvo** [comment]
Ok thank you. I tried it with a different computer and it does seem to work better now.

**Comment by kunalnagar** [comment]
@AndrewCalvo Great! I'll add some sort of indicator when the posts have finished deleting and make it more user-friendly in the next release.

**Comment by kunalnagar** [comment]
@AndrewCalvo @websbydrew Just Released v.2.0.0 of the plugin that has better feedback for clearing logs. Update and try :)
