### ISSUE TITLE
Option to choose "status" missing

### ISSUE THREAD

**Issue by rkorebrits** [kunalnagar/custom-404-pro#13]
404 pages are redirected as the default WordPress 302. 

Ideally the plugin needs a dropdown with options like 302 (default), 404, 301. Cause really a 404 should result in a 404, not a 302. 

https://codex.wordpress.org/Function_Reference/wp_redirect

**Comment by kunalnagar** [comment]
@rkorebrits That's a good suggestion! I'll try and incorporate it in the next release.

**Comment by kunalnagar** [comment]
@rkorebrits So here is how it's gonna work. For the redirect options, I've put a dropdown with two options: 302 (default) and 301. By default, if no redirect is set, you will get a 404. But if you set a redirect, it will choose what you have set from the two options (302 or 301). Hope this makes sense!

**Comment by rkorebrits** [comment]
Hi Kunal, I'm not so sure about this. I've been checking out our logs now, but we are not seeing any 404 messages, but just the default 302. 

What do you mean by "_By default, if no redirect is set, you will get a 404_". How does one set a redirect, or rather, how to not set it? So that we do get 404s.

Why didn't you just add `404` to the drop-down also? I always want 404s to display as 404, so that when we scan the site, we can see which pages aren't redirected to an actual page.
