### ISSUE TITLE
file_get_contents( ) in some hosting is disabled for security

### ISSUE THREAD

**Issue by oloynet** [kunalnagar/custom-404-pro#15]
file_get_contents( ) in some hosting is disabled for security.

To remove the error and have less logs, it possible to had an @ before the function
`$temp   = @file_get_contents( $url );`

[ custom-404-pro/admin/class-custom-404-pro-admin.php ]() - line 326

**Comment by kunalnagar** [comment]
@oloynet Switching to CURL by default. But if that is not installed, the plugin will use `@file_get_contents`
