### ISSUE TITLE
People seeing 404 when they shouldn't be

### ISSUE THREAD

**Issue by paulginsberg** [kunalnagar/custom-404-pro#17]
I've got users seeing 404 error messages when they should actually be seeing profile pages - as soon as I deactivate Custom 404 Pro everything works properly.

e.g. http://www.leaseholdersforum.org.uk/users/paulginsberg/ just displays the 404 but
http://clf.cloud-genius.com/users/paulginsberg/ (my staging website with Custom 404 Pro deactivated) displays the page properly.

Any ideas?  I'm a Wordpress amateur but happy to help troubleshoot/find the source of the issue in any way I can.

Version 1.4.4 is in use.

**Comment by kunalnagar** [comment]
@paulginsberg So this plugin does not allow you to create 404 pages. However, it will allow you to record and redirect your 404s to the default 404 page or to a specific page that you have in WordPress. Hope this helps?

**Comment by paulginsberg** [comment]
Hi @kunalnagar, that doesn't answer the question why people see the correct page (e.g. User Profiles) unless Custom 404 Pro is activated.  Once you activate Custom 404 Pro then they just see the 404 message for these pages.

That said, the functionality works ok most of the time, just not in the User Profiles section.

Samuel Elh has also contacted me regarding this - does that person have any connection with yourself, or have I just been a mug? (luckily no user data compromised!)

**Comment by kunalnagar** [comment]
@paulginsberg I'm not sure what you're talking about. If someone else comes up with the same issue, I'll re-open this up. Thanks.

**Comment by paulginsberg** [comment]
Hi Kunal,

Here's a better explanation:

**Scenario:**
- People on are my BBPress pages: http://www.leaseholdersforum.org.uk/discussion-board/
- They then click a name which should take them to that user's Profile page ("TheLinkIClicked.PNG" - attached)

If Custom 404 is **activated** then then get my custom 404 message ("PageNotFound.PNG").

If Custom 404 is **deactivated** then then they get taken to the correct page and see the correct screen ("WhatShouldHappen.PNG"). e.g. http://www.leaseholdersforum.org.uk/users/paulginsberg/

Hope this fully explanation helps!

Cheers,
Paul
<img width="617" alt="thelinkiclicked" src="https://cloud.githubusercontent.com/assets/5920494/13980556/2e4ef984-f0d7-11e5-841d-c6fbe716d766.PNG">
<img width="684" alt="pagenotfound" src="https://cloud.githubusercontent.com/assets/5920494/13980557/2e58b9f6-f0d7-11e5-9267-5b2a8cef7c56.PNG">
<img width="859" alt="whatshouldhappen" src="https://cloud.githubusercontent.com/assets/5920494/13980562/35d950c8-f0d7-11e5-929f-c00f1b72cb08.PNG">
