### ISSUE TITLE
Lots of log entries

### ISSUE THREAD

**Issue by bzle** [kunalnagar/custom-404-pro#21]
Custom 404 Pro was installed on a site less than a month ago and currently has almost 35,000 entries logged. Our database "postmeta" table has over 500,000 rows, and the custom 404 pro logging appears to be the culprit. Every log results in 17 rows in the table. That makes sense since: 17 x 34,600  = ~500,000.

I've just turned off logging and would like to clear the log soon, but I'll wait in case you want me to check something out for debugging.

Here's an example of one of the logs:

User IP
72.167.190.173

404 Path
/c4p_log/log-34395/

User Agent
WordPress/4.5.2; {{ site url }}  <-- changed for privacy

Redirect
Global Settings Apply (Page)

Date Published
5 hours ago

**Comment by kunalnagar** [comment]
@bzle If you would like to clear the logs, you can click on the Clear Logs button and wait for a while. It deletes in batches of 500. Try refreshing after a minute or two and see the count.

**Comment by bzle** [comment]
@kunalnagar It does take several minutes each time I click "Clear Logs", but it's only deleting around 185 entries. Still have 30,000 to go. Also, the site locks up while it's deleting the entries (so I'm trying to do it late at night).

**Comment by kunalnagar** [comment]
@bzle Just Released v.2.0.0 of the plugin that has better feedback for clearing logs. Update and try :)

**Comment by bzle** [comment]
@kunalnagar I just finished clearing all of them last night! But thanks, I'll grab the update in case turn logging back on.

Any idea what caused the logging to explode like it did? Has that been fixed in v.2.0.0?

**Comment by kunalnagar** [comment]
@bzle I just released a bugfix in 2.0.1. Could you update and let me know if it's working?

**Comment by bzle** [comment]
@kunalnagar After the 500,000 long table I was a bit hesitant to re-enable the plugin, but I finally did and so far so good! Amazing how many people are scanning for a vulnerability. Nice to have the logging feature. Thanks for the fix!

**Comment by kunalnagar** [comment]
@bzle I think if you have 500k logs, there might be something seriously wrong with your website. I would recommend setting up a Google Webmasters and Analytics account to check your 404s. You can then resolve them by removing them from the index manually. (More Info: https://support.google.com/webmasters/answer/1663419?hl=en)

To take a close look at this, export the logs in an Excel format (there are WordPress plugins that allow you to do this), sort them by keyword and work your way through. Hope this helps!
