### ISSUE TITLE
Not showing custom 404 wp site

### ISSUE THREAD

**Issue by JudithSchroeer** [kunalnagar/custom-404-pro#23]
I changed the settings like this:

![grafik](https://cloud.githubusercontent.com/assets/28513240/25785132/62730f30-3379-11e7-8260-fcc44b9ed568.png)

but instead of showing this site: https://letsgetitstraight.de/404-seite/
the default Divi site is shown.
Where do I go wrong?
Thx
Judith

**Comment by kunalnagar** [comment]
I can see the 404 page - can you try changing it to another custom page and see if it works?
