### ISSUE TITLE
Custom 404 causing database error

### ISSUE THREAD

**Issue by streetwitch** [kunalnagar/custom-404-pro#24]
Hi, my custom 404 page is working fine, but I'm getting the following error message which appears multiple times across my wordpress admin screens, especially the menu screen:
"Notice: Undefined index: c4p_log_redirect_to in /home/stereoso/public_html/wp-content/plugins/custom-404-pro/admin/class-custom-404-pro-admin.php on line 167" (various other line refs)
Can you help? Deactivating the plugin stops this from happening, but obviously I'd prefer to have the 404 redirect in place,

Thanks,
SW

**Comment by kunalnagar** [comment]
Can you do a fresh install of the plugin and try again?

**Comment by streetwitch** [comment]
Hi, thanks, but I already tried that, and it didn't make any difference.  I also updated the plugin to the latest version,

**Comment by kunalnagar** [comment]
Hi @streetwitch 

Thanks for the heads up. I've seen this issue pop up before. I'll try and get this sorted out in the next release which should be in a few days.

**Comment by streetwitch** [comment]
Ok thanks, fingers crossed you can – I’ve had to switch it off, and the not found page looks a complete mess,

 

Helen

 

empathydesign

 

t: 01904 399316

m: 07787 411880

http://www.empathydesign.co.uk

**Comment by kunalnagar** [comment]
Hi @streetwitch 

New plugin version released: v2.1.0 Could you please update and let me know if it fixes the issue you're having? Please make sure to uninstall and re-install the plugin for safe measure.

Thanks!
