### ISSUE TITLE
Soft 404

### ISSUE THREAD

**Issue by hhjphoto** [kunalnagar/custom-404-pro#25]
I'm getting a ton of soft 404 errors in the Google Webmaster panel. Do you know what is causing this and why the plug in is not taking care of it?

Thanks!
Here's an example of the error:

http://jansenphotoexpeditions.com/wp-admin/admin-ajax.php?action=PopupBox&current_view=0&fb_id=1&theme_id=0&open_with_fullscreen=0&open_with_autoplay=0&image_width=800&image_height=600&image_effect=fade&enable_image_filmstrip=0&image_filmstrip_height=70&enable_comments=1&enable_likes=1&enable_shares=1&enable_author=1&enable_name=1&enable_place_name=1&enable_message_desc=1&enable_image_ctrl_btn=1&enable_image_fullscreen=1&enable_object_info=0&slideshow_interval=5&enable_image_facebook=0&enable_image_twitter=0&enable_image_google=0&current_url=pagename%3Dwelcome-pnf&image_id=29&image_id=

**Comment by kunalnagar** [comment]
@hhjphoto By default, the log type is set to 302 (soft). You can go and change that in the plugin settings under Settings > General and change it to 404 if you like.
