### ISSUE TITLE
Redirect not working..

### ISSUE THREAD

**Issue by VenusTarot** [kunalnagar/custom-404-pro#26]
hi im using wp super cache with my site. my redirect is sending me to my old 404.php page, which i had renamed so technically it doesnt exist. its still appearing with the theme 404 page instead of my custom page. Whats going on? any help is appreciated.  using SEOSMagazine premium template

**Comment by VenusTarot** [comment]
Notice: Undefined index: c4p_log_redirect_to in /home/www/website.com/wordpress/wp-content/plugins/custom-404-pro/admin/class-custom-404-pro-admin.php on line 166
& same on 167

**Comment by kunalnagar** [comment]
Hi @VenusTarot 

I'm not sure what might be happening. Could you disable WP Super Cache and see if it fixes the issue? Usually, such errors are mostly because of plugins clashing with each other.
