### ISSUE TITLE
404 logs

### ISSUE THREAD

**Issue by Qwadry** [kunalnagar/custom-404-pro#27]
Hello Kunal,

thanks for plugin Custom 404 Pro. Question: how am I supposed to know all the 404 logs and put them to the list? Does it mean all the wrong URL addresses which visitors entered? Thank you for support!

**Comment by Qwadry** [comment]
One more thing: I managed to redirect 404 nonexistent page to my custom WP page, but I need to do it also for "not found" page - can I do it with your plugin? How?

**Comment by kunalnagar** [comment]
Hi @Qwadry 

If there is a 404 on your website, it will redirect to whatever page you have set in the plugin options. Technically speaking, you should not see the default "not found" page if you have configured the settings correctly.
