### ISSUE TITLE
Title Blog

### ISSUE THREAD

**Issue by Aramon** [kunalnagar/custom-404-pro#29]
Hello friend, thanks for this great plugin, I've been looking for something like that for a long time.
I have a request for you, I will certainly like more people, if you could give me immediate advice, I would be grateful to you.
I use the plugin on 3 sites, all of them have the same admin email, so unfortunately I never know which site the bug comes from, because the emauli message does not contain the name or website URL, just the error link in the form:

404 Path | /sitemap-pt-page-2014-09.xml

How do I add a site name to the subject of the message?

**Comment by kunalnagar** [comment]
Hi @Aramon 

Thanks for using the plugin, I'm glad you like it.

Good suggestion to add the site name to the email, I can do that in the next release.

**Comment by kunalnagar** [comment]
Hi @Aramon 

New plugin version released: v2.1.0 You should get the Site title in the email body now :)

Thanks!
