### ISSUE TITLE
Invalid argument supplied for foreach() line 129

### ISSUE THREAD

**Issue by kleinechristoph** [kunalnagar/custom-404-pro#3]
I am getting an error in the wordpress backend saying:

Invalid argument supplied for foreach() in [...]/wp-content/plugins/custom-404-pro/admin/class-custom-404-pro-admin.php on line 129

Wordpress Version 4.2.2.
If you need any more info I think I can reproduce the error after activating the plugin.

**Comment by kunalnagar** [comment]
are you trying to save a custom redirect URL? when does this error occur?

**Comment by kleinechristoph** [comment]
It occured after I set the custom 404-page to a page from my content. (no other custom redirects set)
The warning appears throughout the wordpress backend on top of the pages.

**Comment by kunalnagar** [comment]
sure i was able to reproduce the error, taking a look at it :)

**Comment by kunalnagar** [comment]
@kleinechristoph let me know if it works

**Comment by kleinechristoph** [comment]
@kunalnagar Works > http://internetzkidz.de/not-a-page
Thanks a lot - and amazing speed. 5 stars.

**Comment by kunalnagar** [comment]
:+1:
