### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Brink67** [kunalnagar/custom-404-pro#30]
Awesome, simple and to the point plugin.

A space would be a little helpful in the email sent to the site admin.

Example excerpt from one of my email reports: "...Path/pow-wow/img/a17.pngUser AgentMozilla/5.0 (Windows NT 6.1; Win64; x64)..."
Space is lacking between a17.png and User Agent.

Also even more helpful would be to return the output from $_SERVER["HTTP_REFERER"]; as part of the email report so we could easily find the page with the offending link.

Thanks for consideration.

**Comment by kunalnagar** [comment]
@Brink67 - thanks for using the plugin, I'm glad you like it.

* Could you possibly send a screenshot of how the email looks for you and what change you're talking about? Please make sure to blur out sensitive content.
* Knowing where the 404 came from is a particularly helpful stat. I might add another column in the table as well to show this data (in addition to adding it in the email as well).

**Comment by kunalnagar** [comment]
@Brink67 - released a new version 2.1.1 that contains the Referer update. The referer will show up in the logs table as well as in the email. You should receive the update in an hour or so.

Also, regarding the space issue, the email being sent is an HTML email, but I assume your email client renders a text version which is not supported by the plugin. Here's a screenshot of how the email should look like:

![image](https://user-images.githubusercontent.com/2741371/38125312-2ae2d094-3406-11e8-9929-c2580c609696.png)

Thanks for using the plugin!
