### ISSUE TITLE
Custom 404 Pro Issues

### ISSUE THREAD

**Issue by hhjphoto** [kunalnagar/custom-404-pro#31]
I have the Custom 404 plug in and I am trying to remove it from my Wordpress site and it will not delete. It is throwing a ton of errors. Help!
![404s](https://user-images.githubusercontent.com/29635632/38959342-1da937ce-4315-11e8-830e-481ee9cc3469.jpg)

**Comment by kunalnagar** [comment]
@hhjphoto Please upgrade to version 3.0.0 and you'll find a "Reset" button there that you can use to delete all of these errors. The plugin is re-written from the ground up and incorporates a lot of feedback from users. Let me know if you have any questions, closing this for now.
