### ISSUE TITLE
URL of 404 page

### ISSUE THREAD

**Issue by tripdubpj** [kunalnagar/custom-404-pro#33]
Hey Kunal,

I've set up a custom 404 page within my Wordpress theme, but how do I make sure the incorrect URL e.g. '.com/cndjv' is displayed in the address bar versus the '.com/404' I had to set when creating the new page – when the loaded 404 page is displayed to the user?

Thanks,
Paul

**Comment by kunalnagar** [comment]
@tripdubpj you can set up a redirect to the page you want in the plugin settings. When a 404 is hit, the plugin will redirect to your page of choice.
