### ISSUE TITLE
Not Working with error type 404

### ISSUE THREAD

**Issue by Imbera2017** [kunalnagar/custom-404-pro#34]
I’ve using the mode “Wordpress Page” and I’ve selected a page “Siden finnes ikke”.

But when I’m choosing the 404 under error type it loads the default 404 Genesis page, when I’m using Error Type 302 it displays “Siden finnes ikke”. But it’s important that google and other search engines get 404 and not 302 error type. 

https://elhub.no/

**Comment by kunalnagar** [comment]
@Imbera2017 Thanks for using the plugin!

You can go to the **Plugin Settings** > **General** and set the default Error Type to 404. Remember to Save :)

![image](https://user-images.githubusercontent.com/2741371/41955177-91d754be-79fc-11e8-839d-51edbc3095c6.png)

**Comment by Imbera2017** [comment]
But when I do that, change the Error Type to 404 I doesn't shoe the custome wordpress page - it shows the default Genesis 404 page.

**Comment by Imbera2017** [comment]
The custom 404 page only shows when the error type is 302

**Comment by kunalnagar** [comment]
@Imbera2017 Can you upgrade to version 3.0.0 of the plugin and try out the new version? You will lose your current logs and settings but you should not face these issues, hopefully.
