### ISSUE TITLE
[Feature Request] Log without IP

### ISSUE THREAD

**Issue by JHCD** [kunalnagar/custom-404-pro#35]
Thank you for the nice plugin.

I have a feature request:
Could you please implement an option that prevents the IP address from being stored in the database? 
Is here quite a privacy relevant topic.

Thanks

**Comment by JHCD** [comment]
I would like to have some anchor points for hooks and filters, so that I could add some private code.
e.g. 404 has occurred, 404 stored in DB

**Comment by kunalnagar** [comment]
@JHCD I'll try to add this in 3.0.1 along with some hooks. Can you suggest some useful hooks based on your workflow?

**Comment by kunalnagar** [comment]
@JHCD here's how the Log IP flag will look like in the 3.0.7 update of the plugin:

**Settings:**
![Screen Shot 2019-03-17 at 5 37 55 PM](https://user-images.githubusercontent.com/2741371/54490408-9d8fde80-48db-11e9-94e7-ea5629482cca.png)

**Logs Table:**
![Screen Shot 2019-03-17 at 5 38 25 PM](https://user-images.githubusercontent.com/2741371/54490420-b0a2ae80-48db-11e9-9730-7f57d248f033.png)

**Email:**
![Screen Shot 2019-03-17 at 5 37 30 PM](https://user-images.githubusercontent.com/2741371/54490397-881ab480-48db-11e9-924b-25bd9e1cfb70.png)

**Comment by kunalnagar** [comment]
@JHCD this feature is now in version 3.1.0
