### ISSUE TITLE
[Feature Request] error type 307/308

### ISSUE THREAD

**Issue by JHCD** [kunalnagar/custom-404-pro#36]
Please implement the error type 307/308.
302 is deprecated due to security issues since HTTP / 1.1

See: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection

**Comment by kunalnagar** [comment]
@JHCD  Please upgrade to version 3.0.0 and you'll find the 307/308 redirect error codes there.

The plugin is re-written from the ground up and incorporates a lot of feedback from users. There is an entirely new logging system that does not rely on a custom post type. So if you already have some actions set on your current logs, I would not recommend upgrading.
