### ISSUE TITLE
404 Pro not working

### ISSUE THREAD

**Issue by GlobalCreations** [kunalnagar/custom-404-pro#38]
I just updated Custom 404 Pro to version 3.0.0.  I tried using both a Wordpress page and the link to the page, but neither worked.  Also the settings revert back to 'None' when the settings page reloads.

**Comment by kunalnagar** [comment]
@GlobalCreations can you try the following steps and see if it works?

1. Deactivate and activate the plugin again
2. Save your Settings again
3. See if the 404 redirect works.

We've done a complete re-write of the plugin from the ground up in version 3.0.0 so I appreciate the feedback. I'll be releasing version 3.0.1 with early user feedback such as yourself. Thanks!

**Comment by GlobalCreations** [comment]
Thanks,  It now works.

-Jerry-
Jerry Haugen
Global Creations LLC
PO BOX 5065
KLAMATH FALLS, OR 97603
globalcreations.com


On March 11, 2019 at 7:12:55 PM, Kunal Nagar (notifications@github.com) wrote:

@GlobalCreations can you try the following steps and see if it works?

Deactivate and activate the plugin again
Save your Settings again
See if the 404 redirect works.
We've done a complete re-write of the plugin from the ground up in version 3.0.0 so I appreciate the feedback. I'll be releasing version 3.0.1 with early user feedback such as yourself. Thanks!

**Comment by kunalnagar** [comment]
@GlobalCreations great! In the next version, I'll be adding a button to import your old logs to the new logging model. Would you find that useful? How often do you interact with your 404 logs if any?

**Comment by GlobalCreations** [comment]
I don’t use the logs.  Probably should.

-Jerry-
Jerry Haugen
Global Creations LLC
PO BOX 5065
KLAMATH FALLS, OR 97603
globalcreations.com


On March 11, 2019 at 7:21:51 PM, Kunal Nagar (notifications@github.com) wrote:

@GlobalCreations great! In the next version, I'll be adding a button to import your old logs to the new logging model. Would you find that useful? How often do you interact with your 404 logs if any?
