### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by AndrewCalvo** [kunalnagar/custom-404-pro#4]
It would be great to have the option to turn off the 404 logging.. We recently completely redesigned the site and are getting up to 10 new log entries a minute.

**Comment by kunalnagar** [comment]
How does the logging affect your website?

**Comment by AndrewCalvo** [comment]
The biggest way it affects the site is when I go to create a link using the editor, the "Link to Existing Content" is full of all the log entries, I have to scroll through pages and pages of 'log' entries before I get to an actual page or post that I created

**Comment by kunalnagar** [comment]
I'll take a look at this later today and get back to you. Technically, if you link to existing content, it should not create a log entry.

**Comment by AndrewCalvo** [comment]
I appreciate you looking into this. It's not creating a log entry when I link to an existing content - all of the log entries are showing up in the list of existing content. I cant provide you a screen shot now, but I will tomorrow.

**Comment by kunalnagar** [comment]
Oh I get it now. Since the Log Entry is again a Custom Post Type, it must be showing up in the list of existing content. Damn, that must be irritating. I'll figure out a way to handle this.

**Comment by kunalnagar** [comment]
Deployed version 1.4.0. Please update  and let me know :)
