### ISSUE TITLE
Cannot set 404 page

### ISSUE THREAD

**Issue by mn999** [kunalnagar/custom-404-pro#40]
Hey Kunal,

I am using your plugin since 2 years now and it always worked fine. However, I just noticed that it does not let me set the right 404 page in Wordpress. After hitting save the chosen page is still not set. Do you have any idea? Here is a link to my website: www.mallorca-retreat.com.

Chris

**Comment by kunalnagar** [comment]
Hey Chris,

Can you try deactivating, activating and then save your settings again? If that doesn't work, can you try re-installing the plugin?
