### ISSUE TITLE
Is your plugin is working?

### ISSUE THREAD

**Issue by magneto664** [kunalnagar/custom-404-pro#44]
I don't think your plugin is working on any way. I test it on the two Wordpress sites. on both show me a default wordpress 404 from theme. I test it by custom url and show a page via plugin settings and i do this with TWO wordpress installation both was on different theme. tnx. 
In fast i setup another page with default WP theme and no plugins only yours and is no working. So sorry no your plugin is no working. tnx.

**Comment by kunalnagar** [comment]
@magneto664 thanks for this bug, I'm pushing out a minor bug fix v3.2.11 which should be available soon, please upgrade and let me know if it's working for you :)

**Comment by magneto664** [comment]
I can confirm is working all 2 Wordpress sites and fresh clean installation also working. tnx.
