### ISSUE TITLE
Issue with 404 page

### ISSUE THREAD

**Issue by Cter385** [kunalnagar/custom-404-pro#46]
Hi there,

We had to deactivate the plugin due to it affecting our form submissions and we were wondering if you could fix this error so we could reactivate it and use our custom 404.

[Wed Apr 15 20:08:56.215552 2020] [php7:notice] [pid 6208] [client 134.122.81.145:16988] WordPress database error Table 'wp_beckwood4100.wp_custom_404_pro_options' doesn't exist for query SELECT * FROM wp_custom_404_pro_options /* From [beckwoodpress.com/technology/rapid-prototyping/sites/all/libraries/mailchimp/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php] in [/nas/content/live/beckwood4100/wp-content/plugins/custom-404-pro/admin/AdminClass.php:143] */ made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, AdminClass->custom_404_pro_redirect

**Comment by kunalnagar** [comment]
@Cter385 - thanks for using the plugin!

I'm not sure what this error is. If your current logs are not important to you, could you see if removing the plugin and re-installing fixes the issue?
