### ISSUE TITLE
Bug: Search criteria appears in all page views

### ISSUE THREAD

**Issue by AndrewCalvo** [kunalnagar/custom-404-pro#5]
Since I loaded your plugin, when i go to the "All Posts" or "All Pages" page within WPAdmin it displays the search criteria you have for the log pages (browser, os, browser version). Can that information only appear on the 404 Log page instead of all page lists?

**Comment by kunalnagar** [comment]
Will take a look at this today. Thanks for bringing it up!

**Comment by kunalnagar** [comment]
Deployed version 1.4.0. Please update  and let me know :)
