### ISSUE TITLE
404 Page Error

### ISSUE THREAD

**Issue by Kis0o** [kunalnagar/custom-404-pro#57]
Hi.

Site: www.maikamuyka.com
custom error page: www.maikamuyka.com/not-found-page.html

Instead of redirecting to my custom error page, you get this: "Not Found The requested URL was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."

I have an html site, but a wordpress blog.  There is a wp .htaccess file in the directory that reads:
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteCond %{HTTP_HOST} ^(www\.)?tlgapc\.com$ [NC]
RewriteRule ^(.*)$ https://www.tlgapc.com/$1 [L,R=301]
</IfModule>
# BEGIN WordPress
# The directives (lines) between "BEGIN WordPress" and "END WordPress" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

if I delete the .htaccess file and try to create my own it still doesn't work.  It gives the following error:

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@maikamuyka.tlgapc.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by kunalnagar** [comment]
@Kis0o - is this issue still happening? I was able to go to https://maikamuyka.com/qwe and see a 404 page.
