### ISSUE TITLE
Warning: Undefined array key

### ISSUE THREAD

**Issue by Akiracr** [kunalnagar/custom-404-pro#58]
### Problem:
On general tab there are some warnings messages relate with undefined array keys.

![Selección_352](https://user-images.githubusercontent.com/283008/185441289-7b6fdf2a-523c-42ba-a4f1-960558c6a3d1.png)

When save changes button is used the site brakes showing some similar warnings.
![Selección_353](https://user-images.githubusercontent.com/283008/185443568-b7044c9f-b9b2-4c63-adc2-37635ba4c41e.png)

### More info:
In custom_404_pro_options table the send_email row does not have value.
![Selección_354](https://user-images.githubusercontent.com/283008/185443786-2cd18033-18d8-43cd-923e-3ce17670aac0.png)

**Comment by kunalnagar** [comment]
@Akiracr - thanks for bringing this up, I'll investigate soon. Meanwhile, could you completely remove the plugin and install it again and see if it fixes the issue? Thanks!

**Comment by atheodosis** [comment]
Good evening I am facing this problem. I uninstalled and reinstalled it but the problem persists.

**Comment by yalejandrogg** [comment]
I am also facing this problem. I have tried deactivating/activating, uninstalling/installing but the problem persists as well.

**Comment by kunalnagar** [comment]
@atheodosis @yalejandrogg - could y'all provide some details on: Version of Custom404 Pro and WP Version?

Also, these warnings seem to be related to the General settings - can you play around with setting the email, enabling logging and changing the redirect code and see if it still happens? Thanks!
