### ISSUE TITLE
Why do I receive 404 of pages that I deleted it a while ago?

### ISSUE THREAD

**Issue by karlosdpm** [kunalnagar/custom-404-pro#6]
Hello!

Why do I receive 404 of pages that I deleted it a while ago?
I think the google bot is still crawling them.

For example:

User IP	66.249.65.113
404 Path	/sabrina/author/admin/page/2/
User Agent	Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

What can I do about that?

Thank you!

**Comment by kunalnagar** [comment]
I'm not sure what you mean. 

If you are deleting a page, and then accessing its URL, it will throw a 404 and it will get recorded by the plugin.

**Comment by karlosdpm** [comment]
I never said I accessed the url.

That page was deleted a while ago but still I am receiving that log. 
For example:

User IP 66.249.65.113
404 Path /sabrina/author/admin/page/2/
User Agent Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

That page http://www.kmbytes.com/sabrina/author/admin/page/2/
does not exist anymore, I am not accessing it but I still receive that log.
It is happening for a lot of pages that don't exist anymore.

Why does that happen?

**Comment by kunalnagar** [comment]
If you deleted the page, Google might still have it indexed. So when someone hits that page, a 404 is recorded. You can go to the Webmasters tool and request a URL de-index from Google. 

Hope this helps!
