### ISSUE TITLE
AdminClass.php Error on line 116

### ISSUE THREAD

**Issue by RealAct** [kunalnagar/custom-404-pro#67]
I’m getting thousands of error lines on my logs with the following message:

```
[12-Jul-2023 21:03:45 UTC] PHP Warning: Undefined array key "form-logs-options" in /home/user/public_html/wp-content/plugins/custom-404-pro/admin/AdminClass.php on line 116
[12-Jul-2023 21:03:56 UTC] PHP Warning: Undefined array key "form-logs-options" in /home/user/public_html/wp-content/plugins/custom-404-pro/admin/AdminClass.php on line 116
[12-Jul-2023 21:04:23 UTC] PHP Warning: Undefined array key "form-logs-options" in /home/user/public_html/wp-content/plugins/custom-404-pro/admin/AdminClass.php on line 116

```
It seems I’m not the only one with the error, as others have reported the same on the WordPress support forum.

Are the developers aware and do they have any plans to fix this error?

Thanks.

Unfortunately, I had to disable this plugin until this is fixed. No idea if it’s causing other adverse side effects on my site.

Also, suggestion: It would be a good idea for the developer to create a Pinned topic on WordPress support forum asking users NOT to post support requests there, but here. Many like me post there, unaware that you do not support those forums and people are getting the idea that your plugin is abandoned.

**Comment by kunalnagar** [comment]
Hey @RealAct - thanks for using the plugin - couple of things:

1. I've mentioned it clearly on the description of the plugin that I will not be monitoring the WordPress Support area. 
However, thanks for your recommendation of creating a pinned topic in the Support Forum to make this more visible.
![image](https://github.com/kunalnagar/custom-404-pro/assets/2741371/59c7aec3-6833-4f2a-99d7-e3f0b6d8fbf3)

2. I am not familiar with this error - I will take a look at this and see what might be going on. Can you provide more information about your setup? Is there anything special about it? WordPress version would be a good start. Have you also tried removing the plugin and re-installing it?

3. There are different WordPress setups and this is open-source software. I do what I can to provide regular timely security fixes to the plugin, however I would recommend testing the plugin out on a non-production environment first until you are sure that it works with your setup. There are a lot of people using this plugin without any issues as well.

**Comment by RealAct** [comment]
Thanks, 

I however realized another plugin I use was also doing 4.04 redirections. It's Rank Math SEO, so perhaps both plugins trying to do the same thing was causing the conflict.  

Just posting this here in case someone with the same issue finds this in the future. But I have just uninstalled this plugin and stayed with Rank Math as that would be fewer plugins, plus that one is doing everything I need.

Still, I thank you for your plugin as it is useful, and it definitely can serve thousands of WordPress users.

Regards.
