### ISSUE TITLE
2 Feature Requests

### ISSUE THREAD

**Issue by angelsguitar** [kunalnagar/custom-404-pro#7]
Hi.

First of all, this is a great plugin.  The concept is great and makes it easy to create a custom 404 page.

I would like to request two features that I think would be very practical in managing the logs:

1. Add a "Clear Log" button that allows the entire log to be erased easily with one click

2. Add the option to turn off logging (for those of us who just want to use the 404 page creation without adding a lot of records to the database).

Thanks for your effort on this pluggin.

**Comment by kunalnagar** [comment]
Hi @angelsguitar,

Glad that you like the plugin! Here are my comments:

* I can add the Clear Log button, it will be really useful.
* If you don't want the logging, you can just disable the plugin :)

**Comment by angelsguitar** [comment]
Thanks for your attention to these requests.

**Comment by kunalnagar** [comment]
Deployed version 1.4.0. Please update  and let me know :)

**Comment by angelsguitar** [comment]
Thanks a lot, Kunal!

**Comment by kunalnagar** [comment]
@angelsguitar thanks man! Much appreciated.

**Comment by angelsguitar** [comment]
Hi Kunal.

Sorry that I forgot to share the link in mentioned.  Here is it:

https://angelcandelaria.com/has-personalizado-u-optimizado-la-pagina-de-error-404-de-tu-blog-que-esperas/

**Comment by kunalnagar** [comment]
@angelsguitar Thanks! :+1:
