### ISSUE TITLE
PHP Warning in WordPress admin: Undefined array key "form-logs-options"

### ISSUE THREAD

**Issue by JoaoFreitas2002** [kunalnagar/custom-404-pro#74]
![image](https://github.com/kunalnagar/custom-404-pro/assets/68642811/0e7a918c-3b63-4fe3-9fae-0e60c9fb6469)

The "undefined array key 'form-logs-options'" constantly appears on all admin pages, while the 'tab' only appears on the plugin settings page.

The plugin works fine, however.

**Comment by JoaoFreitas2002** [comment]
You could change the line: 116, code:
`        if( current_user_can( 'administrator' ) && wp_verify_nonce( $_REQUEST['form-logs-options'], 'form-logs-options' ) ) {`
to:
`if( current_user_can( 'administrator' ) && isset( $_REQUEST['form-logs-options'] ) && wp_verify_nonce( $_REQUEST['form-logs-options'], 'form-logs-options' ) ) {`

**Comment by kunalnagar** [comment]
@JoaoFreitas2002 - thanks for the report - I'll look into this!

**Comment by kunalnagar** [comment]
@JoaoFreitas2002 - this should be fixed with the latest release. Please re-open if you still see this issue.
