### ISSUE TITLE
Undefined array key issue (Based on 3.11.0)

### ISSUE THREAD

**Issue by alexclassroom** [kunalnagar/custom-404-pro#78]
After installing and activating this plugin, the following warnings always appear:
Warning: Undefined array key "form-logs-options" in /sitepath/wp-content/plugins/custom-404-pro/admin/AdminClass.php on line 116
Please check it.
Thanks.

**Comment by kunalnagar** [comment]
@alexclassroom - this should be fixed with the latest release. Please re-open if you still face an issue.
