### ISSUE TITLE
Delete link doesn't work

### ISSUE THREAD

**Issue by alexclassroom** [kunalnagar/custom-404-pro#80]
The 'Delete' link under the IP doesn't work. After clicking this link, the record will not be deleted.
![TW001](https://github.com/kunalnagar/custom-404-pro/assets/11472643/99069507-8bc0-4a83-8499-f098ecfd47d4)

**Comment by kunalnagar** [comment]
@alexclassroom - thanks for reporting this issue - i can repro this and will try to have a fix out soon 🙂
